.TH lock 1 2021-08-16

.SH NAME
.B lock
- Bash script around i3lock for a simple, minimal lockscreen.

.SH DESCRIPTION

Use a picture as lockscreen background.

.SH SYNOPSIS

.B lock [options]

.SH OPTIONS

.TP
\fB-i\fP
Set picture to use as lockscreen background.

.TP
\fB-a\fP
Append parameters for i3lock.

.SH SEE ALSO
\fBi3lock\fR(1)

.SH AUTHORS
