.TH lock 1 2021-08-16

.SH NAME
.B lock
- Bash script around i3lock for a simple, minimal and fast lockscreen for any multimonitor setup.

.SH DESCRIPTION

Use a picture as lockscreen background.

.SH SYNOPSIS

.B lock [options]

.SH OPTIONS

.TP
\fB-i\fP
Set picture to use as lockscreen background.

.TP
\fB-a\fP
Append parameters for i3lock.

.TP
\fB-t\fP
Set lock text.

.TP
\fB-f\fP
Set lock text font.

.SH SEE ALSO
\fBi3lock\fR(1)

.SH AUTHORS
